### PR TITLE
Added a failing  test to detect a possible collision

### PR DESCRIPTION
**Pull request by artyuum**
See #145 

This will generate 10 000 hashids in a row and check if there is a collision. I executed the test and it fails.

### CODE REVIEW

**Comment by vinkla** [comment]
Not sure why this fails. `0E97` doesn't show up twice.

**Comment by artyuum** [comment]
I edited the test so you can see the encoded ID that was already generated that conflicts with the new one.

**Comment by vinkla** [comment]
The `testCollision2` test fails:

```php
$hashids = new Hashids();

$this->assertSame('0E97', $hashids->encode(587));
$this->assertSame('0E97', $hashids->encode(25543));
```

I'm guessing this has something to do with the number of ids generated or casing with `array_search`.

**Comment by artyuum** [comment]
I also noticed that manually encoding 587 & 25543 leads to different hashids (which is the expected behavior). The collision happens when we generate lot of hasids in a row. I'm afraid that this library can work for little projects only but won't work for high trafic applications that need to generate a lot of hashids in a row. (even if the passed IDs are different, as you can see in the testCollision() method).

**Comment by vinkla** [comment]
I've updated the test to let you know these numbers don't collide.

**Comment by artyuum** [comment]
Thank you for your time. I executed the test and it doesn't fail. This is really strange. I will come back if I have more information...

**Comment by artyuum** [comment]
**UPDATE**
After further testing, I finally found why I encountered the collision. In my project, I was storing the encoded ID as filename and the filesystem is **case-insensitive** (WSL). But then, when I did some tests using `array_search()` & `in_array()` I didn't set the third argument (strict) as "true", which means that it was doing the test using using loose comparison (case-insentive). Anyway, I'm glad that there is no collision in this library, I'll switch to another filesystem and continue using this library.

**Pull request closed without merging**
