### PR TITLE
encode_hex not working in PHP

### PR DESCRIPTION
**Pull request by NamarsahaM**
It returns blank when I use:

```
$hashids = new Hashids\Hashids();
$hashed_text = $hashids->encode_hex("63706b64");

echo $hashed_text;
```
But it gets hashed when I try:-

```
$hashids = new Hashids\Hashids();
$hashed_text = $hashids->encode_hex("63706b");

echo $hashed_text;
```

### CODE REVIEW

**Comment by vinkla** [comment]
You need to add failing test cases.

**Comment by NamarsahaM** [comment]
> You need to add failing test cases.

it shows blank value.

**Comment by vinkla** [comment]
Add a failing test to the `HashidsTest` class: https://github.com/vinkla/hashids/blob/master/tests/HashidsTest.php

**Comment by NamarsahaM** [comment]
TBH, I am not sure how to add it in test in GitHub. Could you please help me with adding it for me?

```
$hashids = new Hashids\Hashids();
$hashed_text = $hashids->encode_hex("63706b64");

echo $hashed_text;
```

**Comment by vinkla** [comment]
> TBH, I am not sure how to add it in test in GitHub. Could you please help me with adding it for me?

No, I don't have time. I'm closing this. 

If you want to learn more about GitHub: https://guides.github.com/

**Pull request closed without merging**
