### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by dansup**
Add the full provider path to the vendor:publish documentation

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for your contribution. Though, this has already been suggested in #9 and I'll pass on this for now.

**Comment by dansup** [comment]
Can you explain why? It is the best practice.

**Comment by vinkla** [comment]
I think it is fine how it is now.

**Comment by GrahamCampbell** [comment]
> It is the best practice.

Say's who?

**Pull request closed without merging**
