### PR TITLE
update vendor:publish command

### PR DESCRIPTION
**Pull request by hootlex**
publish files only for this package

### CODE REVIEW

**Comment by vinkla** [comment]
This has already been suggested several times. I think it is fine how it is now. Thanks anyway!

**Comment by hootlex** [comment]
The bad thing is that it publishes migrations/options/etc for other packages that someone may don't want to publish.

**Comment by vinkla** [comment]
Yeah that is what bugs me. Why does other packages publish unwanted assets.

**Comment by hootlex** [comment]
Sometimes publishing assets is optional. By running `vendor:publish` all these unwanted/optional assets are being published. Anyway, it's your call. :)

**Pull request closed without merging**
