### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by chrisfranko**

### CODE REVIEW

**Comment by vinkla** [comment]
We're using `::class` notation. It can't be a string. If you want to use it as a string you have to remove the notation in the end.

**Comment by GrahamCampbell** [comment]
This change is wrong.

**Comment by chrisfranko** [comment]
@GrahamCampbell nice pretentious comment

@vinkla I realized that after I haphazardly made the change. :)

Sorry.

**Comment by vinkla** [comment]
No worries.

**Pull request closed without merging**
