### PR TITLE
Fix for lumen

### PR DESCRIPTION
**Pull request by alexw23**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by vinkla** [comment]
Thanks for your contribution but I'm going to pass on this. You can publish and register the configuration from your Lumen application. [Please see the documentation.](http://lumen.laravel.com/docs/installation#configuration-files)

**Comment by alexw23** [comment]
Why wouldn't you make it easier for the next person to come along? Plus isn't the idea to be using ENV variables in laravel regardless of lumen? If you notice laravel 5.1 configs include ENV for this exact reason.

**Comment by vinkla** [comment]
Maybe it would but I don't want to set default environment variables. Thanks for your suggestion though!

**Comment by alexw23** [comment]
For what reason? From my understanding you already are, if that is the case then you should just delete the config.php file all together - I really can't see the concern here. Anyone with existing configs will work as normal, anyone coming on new can (optionally) use ENV variables which are better place to manage (considering they are secrets) rather then committing to source.

**Comment by alexw23** [comment]
Nevertheless I'll setup a fork then - thanks for the chat!

**Comment by GrahamCampbell** [comment]
What! Why on Earth do you need a fork?

**Pull request closed without merging**
