### PR TITLE
Fix PHPDoc of multiByteSplit

### PR DESCRIPTION
**Pull request by szepeviktor**
Discovered by @phpstan

All available PHPDoc Types are to be found on PHPStan's website.
https://phpstan.org/writing-php-code/phpdoc-types

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request Viktor! Please add a link to the documentation for this syntax in the pull request description.

**Comment by szepeviktor** [comment]
Done.

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by vinkla** [comment]
Great! Merged.

**Pull request merged**
