### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/vinkla/hashids/pull/187/commits/4d709b61526435d434a27de6143c6207c7183a6c?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/hashids.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "vinkla/hashids": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by vinkla** [comment]
This is not the Laravel package.

**Comment by jasonmccreary** [comment]
Gotcha. I'll take it off Shift's list. Thanks.

**Comment by vinkla** [comment]
I know its confusing:

- the `vinkla/hashids` repository is `hashids/hashids` package 
- and `vinkla/laravel-hashids` repository is the `vinkla/hashids` Laravel package

If you feel up for it, please submit a pull request to https://github.com/vinkla/laravel-hashids

**Pull request closed without merging**
