### PR TITLE
Added extension tests

### PR DESCRIPTION
**Pull request by vinkla**
This pull request run the tests against both `gmp` and `bc` extensions.

### CODE REVIEW

**Comment by vinkla** [comment]
Not really sure how to solve this. I want to run the test suite against both `gmp` and `bcmath` since we allow both extensions in the library:

https://github.com/vinkla/hashids/blob/7cfb2d6e651906d05c71c9332f5f5a7051e8ed1b/src/Hashids.php#L398-L409

@shivammathur do you know how this could be solved?

**Comment by artyuum** [comment]
What if you add a fourth optional argument to the constructor? Then you'll be able to test both and it will also give the users of this library the ability to choose which extension to use.

Example: 
```php
public function __construct($salt = '', $minHashLength = 0, $alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', $mathExtension = null) {}
```

**Comment by vinkla** [comment]
Thanks for the suggestion @artyuum. 

I do understand the idea but I don't want to introduce a fourth option in order to make the test turn green. Also, this request hasn't come up before. It is most likely something users of this library wont care about.

**Comment by shivammathur** [comment]
@vinkla Add conditional logic to your `DataProvider` in `MathInterfaceTest.php`.

```php
public function mathProvider()
{
    if (\extension_loaded('gmp')) {
        return [
            [new Gmp()]
        ];
    }

    if (\extension_loaded('bcmath')) {
        return [
            [new Bc()]
        ];
    }

    throw new RuntimeException('Missing BC Math or GMP extension.'); 
}
```

**Comment by vinkla** [comment]
Thanks @shivammathur! Since both `gmp` and `bcmath` are enabled by default, is it correct to disable them in this case or is there a better way?

https://github.com/vinkla/hashids/blob/da7e8428e1c285650c88ab9aa5a7423384126dae/.github/workflows/ci.yml#L12

**Comment by shivammathur** [comment]
@vinkla  Workflow seems fine to me.

**Pull request merged**
